name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix:
        destination:
          - "platform=macOS"

    steps:
      - uses: actions/checkout@v3
      - name: Test platform ${{ matrix.destination }}
        run: swift test
